import { MissionCheckpoint } from "../Aerofly/MissionCheckpoint.js";
import { GarminExportAbstract } from "../Import/GarminFpl.js";
import { LonLat } from "../World/LonLat.js";

export class MainMcfExport extends GarminExportAbstract {
  toString(): string {
    let mcf = `\
// This is not a complete main.mcf file. It only contains the aircraft, time &
// date, weather and route settings.
// You need to copy this into an existing main.mcf file to use it in Aerofly FS.
// Consider only the settings indented with 8 spaces or more as relevant for the
// mission.

// Generated by Aerofly Missionsgerät
<[file][][]
    <[tmsettings_sim][][]
// -----------------------------------------------------------------------------
        <[tmsettings_aircraft][aircraft][]
            <[string8u][name][${this.mission.aircraft_name}]>
            <[string8][paintscheme][${this.mission.aircraft_livery}]>
            <[list_string8][options][]>
            <[bool][profi][false]>
        >
        <[tmsettings_flight][flight_setting][]
            <[vector3_float64][position][${this.convertCoordinates(this.mission.origin_lon_lat).join(
              " "
            )}]> // lon lat: ${this.mission.origin_lon_lat.toString()}
            <[vector3_float64][velocity][0 0 0]>
            <[matrix3_float64][orientation][${this.convertOrientation(this.mission.origin_dir).join(" ")}]>
            <[float64][gear][1]>
            <[float64][throttle][0]>
            <[float64][flaps][0]>
            <[flight_configuration][configuration][Keep]>
            <[bool][on_ground][true]>
            <[string8u][airport][]>
            <[string8u][runway][]>
        >
        <[tmsettings_fuel_load][fuel_load_setting][]
            <[fuel_load_configuration][configuration][Keep]> // or "Invalid"
            <[string8u][aircraft][${this.mission.aircraft_name}]>
            <[float64][fuel_mass][0]>
            <[float64][payload_mass][0]>
        >
// -----------------------------------------------------------------------------
        <[tm_time_utc][time_utc][]
            <[int32][time_year][${this.mission.conditions.time.time_year}]>
            <[int32][time_month][${this.mission.conditions.time.time_month}]>
            <[int32][time_day][${this.mission.conditions.time.time_day}]>
            <[float64][time_hours][${this.mission.conditions.time.time_hours}]>
        >
        <[float64][visibility][${this.mission.conditions.visibility_percent}]>
        <[tmsettings_wind][wind][]
            <[float64][strength][${this.mission.conditions.wind_speed_percent}]>
            <[float64][direction_in_degree][${this.mission.conditions.wind_direction}]>
            <[float64][turbulence][${this.mission.conditions.turbulence_strength}]>
            <[float64][thermal_activity][${this.mission.conditions.thermal_strength}]>
        >
        <[tmsettings_clouds][clouds][]
            <[float64][cumulus_density][${this.mission.conditions.cloud.cover}]>
            <[float64][cumulus_height][${this.mission.conditions.cloud.height_percent}]>
            <[float64][cumulus_mediocris_density][${this.mission.conditions.cloud2.cover}]>
            <[float64][cumulus_mediocris_height][${this.mission.conditions.cloud2.height_percent}]>
            <[float64][cirrus_height][${this.mission.conditions.cloud3.cover}]>
            <[float64][cirrus_density][${this.mission.conditions.cloud3.height_percent}]>
        >
// -----------------------------------------------------------------------------
        <[tmnavigation_config][navigation][]
            <[tmnav_route][Route][]
                <[float64][CruiseAltitude][${this.mission.cruise_altitude ?? -1}]>
                <[pointer_list_tmnav_route_way][Ways][]
`;
    mcf += this.mission.checkpoints
      .map((wp, id) => {
        let additional = "";

        switch (wp.type) {
          case MissionCheckpoint.TYPE_ORIGIN:
          case MissionCheckpoint.TYPE_DESTINATION:
          case MissionCheckpoint.TYPE_DEPARTURE_RUNWAY:
          case MissionCheckpoint.TYPE_DESTINATION_RUNWAY:
            additional += `\
                        <[bool][Elevation][${wp.lon_lat.altitude_m}]> // ${wp.lon_lat.altitude_ft.toFixed(0)} ft
`;
            break;
          default:
            additional += `\
                        <[bool][FlyOver][${wp.flyOver ? "true" : "false"}]>
                        <[bool][Altitude][${wp.lon_lat.altitude_m || -1001} ${wp.lon_lat.altitude_m || 100001}]> // ${
              wp.lon_lat.altitude_ft ? wp.lon_lat.altitude_ft.toFixed(0) + " ft" : "unrestricted"
            }
`;
            if (wp.frequency) {
              additional += `\
                        <[uint32][NavaidFrequency][${wp.frequency}]> // ${wp.frequency_string}
`;
            }
            break;
        }

        return `\
                    <[tmnav_route_${wp.type}][${wp.name}][${id}]
                        <[string8u][Identifier][${wp.name}]>
                        <[vector3_float64][Position][${this.convertCoordinates(wp.lon_lat).join(
                          " "
                        )}]> // lon lat: ${wp.lon_lat.toString()}
                        // <[uint64][Uid][]>
${additional}\
                    >
`;
      })
      .join("");
    mcf += `\
                >
            >
        >
// -----------------------------------------------------------------------------
    >
>
`;
    return mcf;
  }

  /**
   *
   * @param direction Orientation of aircraft in degree
   * @returns Cartesian matrix
   */
  protected convertOrientation(
    direction: number
  ): [number, number, number, number, number, number, number, number, number] {
    const theta = direction * (Math.PI / 180); // direction in radians

    const cosTheta = Math.cos(theta);
    const sinTheta = Math.sin(theta);

    return [cosTheta, -sinTheta, 0, sinTheta, cosTheta, 0, 0, 0, 1];
  }

  protected convertCoordinates(lonLat: LonLat): [number, number, number] {
    const a = 6378137.0;
    const f = 1.0 / 298.257223563;
    const e2 = f * (2 - f);

    const lon = lonLat.lonRad;
    const lat = lonLat.latRad;
    const h = lonLat.altitude_m;

    const sinLat = Math.sin(lat);
    const cosLat = Math.cos(lat);
    const cosLon = Math.cos(lon);
    const sinLon = Math.sin(lon);

    const N = a / Math.sqrt(1 - e2 * sinLat * sinLat);
    const x = (N + h) * cosLat * cosLon;
    const y = (N + h) * cosLat * sinLon;
    const z = (N * (1 - e2) + h) * sinLat;

    return [x, y, z];
  }
}
